export enum ErrorCode {
  VERIFY_COLLECTION = "VERIFY_COLLECTION",
  CREATE_COLLECTION = "CREATE_COLLECTION",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  APP_ERROR = "APP_ERROR",
  AUTH_REGISTER = "AUTH_REGISTER",
  AUTH_LOGIN = "AUTH_LOGIN",
  AUTH_LOGOUT = "AUTH_LOGOUT",
}
